adapterhandshake:
  host: "meg-dev-adapter-handshake.uk-e1.cloudhub.io"
  port: "8092"
  basepath: "/v1-0"
  client_id: "adapterclientId"
  client_secret: "adapterClientSecret"
  correlationId: "adapterCorrelationid"
anypointmq:
  url: "https://mq-eu-west-2.anypoint.mulesoft.com/api/v1"
  clientid: "e6783be2d3894aac926b39f2c4fc0cd8"
  clientsecret: "6c05D064Ca144d5188Ac3673aE89393B"
  grantaccessexchange: "exc-access.control.grant"
  grantaccessqueue: "queue-access.control.grant"
  updateaccessexchange: "exc-access.control.update"
  updateaccessqueue: "queue-access.control.update"
  restoreaccessexchange: "exc-access.control.restore"
  restoreaccessqueue: "queue-access.control.restore"
  suspendaccessexchange: "exc-access.control.suspend"
  suspendaccessqueue: "queue-access.control.suspend"