http:
  host: "0.0.0.0"
  port: "8082"
  basepath: "/api/"

connection:
  idle:
    timeout: "90000"

password:
  key: "H65Y34de78rr786g"
  
keystore:
  password: "![FyIHaLDB8dxZOj+Z4/aCTA==]"
  
api:
  key: "15675041"
  
cloudhub:
  env: "sdlc-dev-livetest"
  domain: "sdlc-dev-meg-b2c-mobile"
  user: "cloudhubnotifications@sdlc-dev-livetest"
  pwd: "![GQvJOEoit7PTGG44endjHQ==]"
  disable:
    alert: "false"
    
anypointmq:
  url: "https://mq-eu-west-2.anypoint.mulesoft.com/api/v1"
  clientid: "e6783be2d3894aac926b39f2c4fc0cd8"
  clientsecret: "6c05D064Ca144d5188Ac3673aE89393B"
  grantaccessexchange: "exc-access.control.grant"
  grantaccessqueue: "queue-access.control.grant"
  updateaccessexchange: "exc-access.control.update"
  updateaccessqueue: "queue-access.control.update"
  restoreaccessexchange: "exc-access.control.restore"
  restoreaccessqueue: "queue-access.control.restore"
  suspendaccessexchange: "exc-access.control.suspend"
  suspendaccessqueue: "queue-access.control.suspend"
    